### ISSUE TITLE
未追加のライブラリ

### ISSUE THREAD

**Issue by sudachi0114** [sudachi0114/rshell#2]
[参考元 のリポジトリ](https://github.com/garebareDA/g_shell)のコミット `7701985` で追加しているライブラリをまだ追加してない

⬇️ `Cargo.toml`

```toml
[dependencies]
nix = "0.19.0"
termion = "*"
```
